### ISSUE TITLE
Ajout d'une section "c'est quand les prochaines grèves ?"

### ISSUE THREAD

**Issue by numahell** [Signez/grevepointcool#24]
Avec par exemple un lien vers le site https://www.cestlagreve.fr/ (mais il a un tracker vers https://quantcast.mgr.consensu.org/).

Sinon ce site est super, merci !

**Comment by Signez** [comment]
Hey @numahell ! Je pense que faire la liste des grèves en cours ou à venir sort un peu du périmètre de ce que je souhaite pour ce site, qui semble plutôt pertinent comme une information _« générale »_ sur les grands mouvements de grèves interprofessionnelles.

Merci pour ces gentils mots par ailleurs :)
