### ISSUE TITLE
Nomenclature 

### ISSUE THREAD

**Issue by imgrangerdanger** [Signez/grevepointcool#32]
Merci pour ce très chouette (fonctionnel, informatif, tour ce qu'on veut) site !

Juste : on dit surveillant.e.s pénitentiaires et non gardien.ne.s de prison :) (depuis plus de 100 ans maintenant ! The more you know)

**Comment by imgrangerdanger** [comment]
@Signez Désolée mais du coup on dit "pénitentiaires" et pas "pénitenciers" :) Merci pour la réactivité !!

**Comment by Signez** [comment]
Ah ! Merci de l'info, je corrige ça tout de suite :)

**Comment by imgrangerdanger** [comment]
Top, merci !! :)
