### ISSUE TITLE
Comment se faire compter

### ISSUE THREAD

**Issue by supermamie** [Signez/grevepointcool#33]
Est ce qu’il y a un moyen d’être compté dans le nombre de français en grève ?
Et si oui, comment ?

Il y aura les décomptes des manifestants dans les grandes villes, mais pour les "autres", comment faire ? Est ce que l’employeur remontera l’info de lui même ?
Et dans le cas d’un·e indépendant·e ?

**Comment by Signez** [comment]
À ma connaissance, il n’existe pas de "décompte" ou de remontée officielle du nombre de grévistes en France. On peut le déplorer, et en même temps, les instruments qui permettraient de le faire pourraient (selon comment ils sont conçus) être utilisés à mauvais escients pour cibler celles et ceux qui y prennent part — pas sûr que le jeu en vaut la chandelle !

Néanmoins, comme indiqué sur le site, le fait qu’il n’y aie pas de décompte chiffré précis ne veut pas dire que cela n’a pas d’impact : en terme économique, ces journées entières de production perturbée peuvent peser sur les entreprises, ce qui peut ensuite les inciter à peser à leur tour sur les pouvoirs politiques et sur les syndicats patronaux.

Dans le cas des indépendants, la question reste ouverte — la grève pour un indépendant n’a pas vraiment de sens (vu qu’on n’est pas dans un contrat de travail) mais cela n’empêche pas de pouvoir revendiquer sa participation « sur le principe » et de relayer les actions qui sont faites.

J’espère que ça répond à tes questions ! Ce sont mes considérations personnelles — et ce sont des questions qui n’avaient pas vraiment été posées par le passé, donc je ne sais pas à quel point on pourrait les intégrer à la page qu’on a volontairement voulu garder simple… mais ça va clairement rester dans un coin de ma tête :)
