### ISSUE TITLE
Mot doux

### ISSUE THREAD

**Issue by gorlanova** [Signez/grevepointcool#34]
Je ne savais pas par quel canal passer : aucun souci avec le site, il est super !
Je voulais simplement dire merci et si il y a besoin de quoi que ce soit, je suis dev web et je serais ravie de contribuer

❤️

**Comment by Signez** [comment]
Haha, merci ! J’avais créé ce site durant une pause déjeuner en 2019, et j’ai eu la chance d’avoir de nombreuses petites contributions et relectures de la part d’amis et de camarades inconnus des Internets. Ravi qu’il puisse être utile ! ✨

Je pense que la manière la plus simple désormais de contribuer reste d’en parler autour de soi, et d’espérer que cela convainc — ou en tout cas dédramatise — certain·e·s de faire grève à leur tour, peut-être pas cette fois-ci, mais peut-être la fois suivante, comme ont réussi à le faire d’anciens collègues devenus amis il y a plusieurs années :)
