### ISSUE TITLE
Écriture inclusive non necessaire

### ISSUE THREAD

**Issue by Richalbert** [Signez/grevepointcool#37]
cool page
juste une remarque relatif a l ecriture inclusive qui est tres desagreable a voir puis a lire et qui n apporte pas de valeur ajoute au texte (voir dessert le message)
pourquoi ne pas se retrouver/rassembler autour de la langue francaise tel qu elle est tout simplement comme denominateur commun
fin de la remarque 
sinon bonne page avec un github

**Comment by Signez** [comment]
L’Internet est vaste ! N’hésitez pas à créer votre propre page sur votre site, où vous pourrez formuler vos idées comme vous le souhaitez.

L’écriture inclusive utilisée, avec des points médians, est un choix délibéré dont la remise en cause n’est pas à l’ordre du jour.
