### ISSUE TITLE
Exemples de succès récents

### ISSUE THREAD

**Issue by Malba38** [Signez/grevepointcool#38]
Bonjour,

Tout d'abord, merci beaucoup pour ce site qui m'a permis de beaucoup mieux comprendre mes droits et mes moyens d'actions.
J'ai cependant l'impression que la partie "j'ai l'impression que ça sert à rien" manque d'exemples de grèves avec résultats probants comme j'ai pu en voir sur reddit récemment.

Mais collègues se sont moqués de moi jeudi il y a 2 semaines en me disant que ça servait à rien, avoir une bonne source pour leur expliquer qu'ils se trompent serait plus efficace il me semble.

J'aimerai utiliser ce site pour convertir des gens qui pensent que ça ne sert à rien, je voudrais plus de billes pour ça !

Merci encore pour votre boulot, bonne continuation et à demain :-)

**Comment by adhumi** [comment]
Dans les exemples pas trop vieux, on peut citer :
- [Ibis Les Batignolles](https://fr.wikipedia.org/wiki/Mobilisation_des_femmes_de_chambre_de_l%27hôtel_Ibis_Batignolles)
- [GRDF](https://www.liberation.fr/economie/social/greve-chez-grdf-la-cgt-et-la-direction-trouvent-un-accord-apres-six-semaines-de-conflit-20221220_66ZEHBC4GBEILJWJR7YSFD4K24/)
- [Geodis](https://www.lefigaro.fr/conjoncture/plateforme-geodis-a-gennevilliers-la-greve-levee-apres-un-accord-avec-la-direction-20221118)

**Comment by Signez** [comment]
J’ai rajouté quelques exemples avec ce commit (https://github.com/Signez/grevepointcool/commit/5cf2aafb0163e4dfcad394b03bff3c331751ea85), mais si vous en avez d’autres ou si vous avez des avis sur la formulation, n’hésitez pas :)

**Comment by Signez** [comment]
Je me permet de fermer cette issue, vu que les exemples ont été rajoutés et que ça semble suffire pour l'instant sur le site. Merci encore de la participation !
