### ISSUE TITLE
Syndicalisme.cool

### ISSUE THREAD

**Issue by D4llo** [Signez/grevepointcool#52]
Hello,

Que pensez-vous du fork sur le syndicalisme qu'est https://syndicalisme.cool/ ?

Est-ce que ça vaudrait le coup de le mettre dans les liens utiles ?

Bonne journée :)

**Comment by Signez** [comment]
Hey ! Je trouve ça très chouette. Je vais voir comment rajouter un lien vers ça dans les liens utiles :)

**Comment by Signez** [comment]
C'est fait ! Y'a désormais un lien vers [syndicalisme.cool](https://syndicalisme.cool/) (6672961fdf87e8cbdf811415c4d50d4ab85509a0).

**Comment by D4llo** [comment]
Trop cool ! Encore merci pour le taf !
